const servicesList = [
    { name: 'Angioplasty', cost: 5000 },
    { name: 'Anesthesia', cost: 300 },
    { name: 'Arthroscopy', cost: 4000 },
    { name: 'Biopsy', cost: 700 },
    { name: 'Blood Tests', cost: 100 },
    { name: 'Cancer Screening', cost: 1500 },
    { name: 'Cardiac Catheterization', cost: 8000 },
    { name: 'Cardiovascular Surgery', cost: 20000 },
    { name: 'Chemotherapy', cost: 5000 },
    { name: 'Consultation', cost: 50 },
    { name: 'Counseling', cost: 100 },
    { name: 'CT Scan', cost: 700 },
    { name: 'Dermatology', cost: 100 },
    { name: 'Echocardiogram', cost: 1500 },
    { name: 'ECG/EKG', cost: 300 },
    { name: 'Emergency Room Visit', cost: 200 },
    { name: 'Endocrinology', cost: 150 },
    { name: 'ENT Surgery', cost: 3000 },
    { name: 'Follow-up Visit', cost: 50 },
    { name: 'Fracture Treatment', cost: 500 },
    { name: 'Gastroenterology', cost: 200 },
    { name: 'General Consultation', cost: 50 },
    { name: 'General Surgery', cost: 5000 },
    { name: 'Gynecological Surgery', cost: 6000 },
    { name: 'ICU Stay', cost: 1000 },
    { name: 'Immunizations', cost: 50 },
    { name: 'Inpatient Psychiatric Care', cost: 2000 },
    { name: 'Inpatient Rehabilitation', cost: 1000 },
    { name: 'Intensive Care Unit (ICU) Stay', cost: 1500 },
    { name: 'Joint Replacement', cost: 20000 },
    { name: 'Labor and Delivery', cost: 3000 },
    { name: 'Laboratory Tests', cost: 150 },
    { name: 'Mammography', cost: 500 },
    { name: 'MRI', cost: 1000 },
    { name: 'Neonatal Intensive Care Unit (NICU)', cost: 3000 },
    { name: 'Nephrology', cost: 150 },
    { name: 'Neurosurgery', cost: 20000 },
    { name: 'Nutritional Counseling', cost: 100 },
    { name: 'Occupational Therapy', cost: 150 },
    { name: 'Oncology Surgery', cost: 15000 },
    { name: 'Ophthalmic Surgery', cost: 5000 },
    { name: 'Orthopedic Surgery', cost: 10000 },
    { name: 'Outpatient Rehabilitation', cost: 500 },
    { name: 'Pain Management', cost: 300 },   
    { name: 'Pacemaker Implantation', cost: 15000 },
    { name: 'Pediatric Consultation', cost: 50 },
    { name: 'Pediatric Surgery', cost: 7000 },
    { name: 'Pharmacy Services', cost: 50 },
    { name: 'Physical Therapy', cost: 150 },
    { name: 'Prenatal Care', cost: 200 },
    { name: 'Psychiatric Consultation', cost: 200 },
    { name: 'Radiation Therapy', cost: 7000 },
    { name: 'Respiratory Therapy', cost: 200 },
    { name: 'Rheumatology', cost: 150 },
    { name: 'Stress Test', cost: 500 },
    { name: 'Surgery', cost: 10000 },
    { name: 'Trauma Care', cost: 2000 },
    { name: 'Ultrasound', cost: 300 },
    { name: 'Urological Surgery', cost: 8000 },
    { name: 'Urine Tests', cost: 100 },
    { name: 'X-Ray', cost: 200 }
  ];
  
  export default servicesList;
  